name = "orderClosures"
version = "0.1.0"
keywords = ["math", "banach-lattices", "order-convergence"]
defaultTargets = ["OrderClosures"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false

[[require]]
name = "banLat"
git = "https://github.com/davidmunozlahoz/banlat"
rev = "b00e59836016aa1099b8011add6b07385e66428e"

[[lean_lib]]
name = "OrderClosures"
